[package]
name = "lv2rs-urid"
version = "0.1.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/Janonard/lv2rs-urid"
exclude = [".vscode/*", "urid-test"]
description = "Rust re-implementation of the LV2 core library"
edition = "2018"

[dependencies]
lv2rs-core = "0.2.0"