[package]
name = "lv2rs"
version = "0.2.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "ISC"
readme = "README.md"
repository = "https://github.com/Janonard/lv2rs"
exclude = [".vscode/*", "*.json"]
description = "Rust re-implementation of the LV2 libraries"
edition = "2018"

[dependencies]
lv2rs-core = "0.2.0"
lv2rs-urid = "0.1.0"