[package]
name = "lv2rs"
version = "0.1.0"
authors = ["Janonard <janonard@protonmail.com>"]
license = "LGPL-3.0"
readme = "README.md"
repository = "https://github.com/Janonard/lv2rs"
exclude = [".vscode/*",]
description = "Rust re-implementation of the LV2 libraries"
edition = "2018"

[dependencies]
lv2rs-core = "0.1.1"